<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 16, 2016 23:32PM</p>

           <p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'authentifier.users' doesn't exist</p>

           <p><strong>Code:</strong> 42S02</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(64): Helpers\Database->select('SELECT user_id ...', Array, 2)
#2 /app/app/Modules/Authentifier/Controllers/Login.php(54): Modules\Authentifier\Models\UserModel->selectID('jerome')
#3 /app/app/Modules/Authentifier/Controllers/Login.php(46): Modules\Authentifier\Controllers\Login->loginActionDatabase('jerome', 'harley')
#4 [internal function]: Modules\Authentifier\Controllers\Login->loginAction()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 17, 2016 21:05PM</p>

           <p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'authentifier.users' doesn't exist</p>

           <p><strong>Code:</strong> 42S02</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(64): Helpers\Database->select('SELECT user_id ...', Array, 2)
#2 /app/app/Modules/Authentifier/Controllers/Login.php(54): Modules\Authentifier\Models\UserModel->selectID('admin')
#3 /app/app/Modules/Authentifier/Controllers/Login.php(46): Modules\Authentifier\Controllers\Login->loginActionDatabase('admin', '********')
#4 [internal function]: Modules\Authentifier\Controllers\Login->loginAction()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<p>Error on Mar 17, 2016 21:17PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><p>Error on Mar 17, 2016 21:17PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><p>Error on Mar 17, 2016 21:18PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><p>Error on Mar 17, 2016 21:18PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><p>Error on Mar 17, 2016 21:18PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><p>Error on Mar 17, 2016 21:19PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><p>Error on Mar 17, 2016 21:19PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><p>Error on Mar 17, 2016 21:19PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><p>Error on Mar 17, 2016 21:19PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><p>Error on Mar 17, 2016 21:19PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 19, 2016 9:49AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'authentifier.users' doesn't exist</p>

           <p><strong>Code:</strong> 42S02</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(53): Helpers\Database->select('SELECT user_id ...', Array, 2)
#2 /app/app/Modules/Authentifier/Models/UserModel.php(61): Modules\Authentifier\Models\UserModel::selectID('Quentin')
#3 /app/app/Modules/Authentifier/Controllers/Register.php(103): Modules\Authentifier\Models\UserModel::exist('Quentin')
#4 /app/app/Modules/Authentifier/Controllers/Register.php(61): Modules\Authentifier\Controllers\Register->registerFormDataValidation(false)
#5 [internal function]: Modules\Authentifier\Controllers\Register->registerAction()
#6 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#7 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#8 /app/app/Core/routes.php(29): Core\Router::dispatch()
#9 /app/index.php(81): require('/app/app/Core/r...')
#10 {main}</pre>

           <hr />
<p>Error on Mar 19, 2016 11:57AM - require(/app/app/templates/default//Authentifier/Views/Admin/index_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 62</p><p>Error on Mar 19, 2016 11:57AM - require(/app/app/templates/default//Authentifier/Views/Admin/index_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 62</p><p>Error on Mar 19, 2016 11:57AM - require(/app/app/templates/default//Authentifier/Views/Admin/index_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 62</p><p>Error on Mar 19, 2016 11:57AM - require(/app/app/templates/default//Authentifier/Views/Admin/index_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 62</p><p>Error on Mar 19, 2016 11:59AM - require(/app/app/templates/default//Authentifier/Views/Admin/index_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 62</p><p>Error on Mar 19, 2016 11:59AM - require(/app/app/templates/default/index_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 62</p><p>Error on Mar 19, 2016 11:59AM - require(/app/app/templates/default/index_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 62</p><p>Error on Mar 19, 2016 12:00PM - require(/app/app/templates/default/index_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 62</p><p>Error on Mar 19, 2016 12:00PM - require(/app/app/views/index_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:00PM - require(/app/app/views/index_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:09PM - require(/app/app/error/404.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:09PM - require(/app/app/index.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:10PM - require(/app/app/index.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:14PM - require(/app/app/view/Modules/Authentifier/Views/Admin/user_management_panel_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:14PM - require(/app/app/view/index.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:14PM - require(/app/app/view/Modules/Authentifier/Views/Admin/user_management_panel_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:14PM - require(/app/app/view/index.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:16PM - require(/app/app/view/index.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:16PM - require(/app/app/view/index.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:16PM - require(/app/app/view/index.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:16PM - require(/app/app/view/Modules/Authentifier/Views/Admin/user_management_panel_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:16PM - require(/app/app/view/index.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:18PM - require(/app/app/view/index.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:18PM - require(/app/app/view/index.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:18PM - require(/app/app/view/Modules/Authentifier/Views/Admin/user_management_panel_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:20PM - require(/app/app/view/Modules/Authentifier/Views/Admin/index_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:20PM - require(/app/app/view/Modules/Authentifier/Views/Admin/index_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:20PM - require(/app/app/view/Modules/Authentifier/Views/Admin/index_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:20PM - require(/app/app/view/error/404.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 19, 2016 12:47PM - Missing argument 1 for Modules\Authentifier\Controllers\Admin::usersManagementElement() in /app/app/Modules/Authentifier/Controllers/Admin.php on line 41</p><p>Error on Mar 19, 2016 12:47PM - require(/app/app/Modules//Authentifier/Views/Admin/users_management_panel_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 19, 2016 12:47PM - require(/app/app/Modules//Authentifier/Views/Admin/users_management_panel_header.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 19, 2016 13:14PM</p>

           <p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'authentifier.users' doesn't exist</p>

           <p><strong>Code:</strong> 42S02</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(53): Helpers\Database->select('SELECT user_id ...', Array, 2)
#2 /app/app/Modules/Authentifier/Controllers/Login.php(56): Modules\Authentifier\Models\UserModel::selectID('alex62d')
#3 /app/app/Modules/Authentifier/Controllers/Login.php(48): Modules\Authentifier\Controllers\Login->loginActionDatabase('alex62d', 'cccd0608')
#4 [internal function]: Modules\Authentifier\Controllers\Login->loginAction()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<p>Error on Mar 19, 2016 13:15PM - call_user_func_array() expects parameter 1 to be a valid callback, class 'Modules\Authentifier\Controllers\Authentifier' does not have a method 'test' in /app/app/Core/Router.php on line 126</p><p>Error on Mar 19, 2016 13:24PM - call_user_func_array() expects parameter 1 to be a valid callback, class 'Modules\Authentifier\Controllers\Authentifier' does not have a method 'test' in /app/app/Core/Router.php on line 126</p><p>Error on Mar 19, 2016 13:24PM - call_user_func_array() expects parameter 1 to be a valid callback, class 'Modules\Authentifier\Controllers\Authentifier' does not have a method 'test' in /app/app/Core/Router.php on line 126</p><p>Error on Mar 19, 2016 13:24PM - call_user_func_array() expects parameter 1 to be a valid callback, class 'Modules\Authentifier\Controllers\Authentifier' does not have a method 'test' in /app/app/Core/Router.php on line 126</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 19, 2016 17:08PM</p>

           <p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'authentifier.users' doesn't exist</p>

           <p><strong>Code:</strong> 42S02</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/AdminModel.php(17): Helpers\Database->select('SELECT user_nam...', Array, 2)
#2 /app/app/Modules/Authentifier/Controllers/Admin.php(29): Modules\Authentifier\Models\AdminModel::selectAllUsers()
#3 [internal function]: Modules\Authentifier\Controllers\Admin->usersManagementPanel()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 19, 2016 17:19PM</p>

           <p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'authentifier.users' doesn't exist</p>

           <p><strong>Code:</strong> 42S02</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(53): Helpers\Database->select('SELECT user_id ...', Array, 2)
#2 /app/app/Modules/Authentifier/Controllers/Login.php(56): Modules\Authentifier\Models\UserModel::selectID('admin')
#3 /app/app/Modules/Authentifier/Controllers/Login.php(48): Modules\Authentifier\Controllers\Login->loginActionDatabase('admin', '********')
#4 [internal function]: Modules\Authentifier\Controllers\Login->loginAction()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 19, 2016 17:20PM</p>

           <p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'authentifier.users' doesn't exist</p>

           <p><strong>Code:</strong> 42S02</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(53): Helpers\Database->select('SELECT user_id ...', Array, 2)
#2 /app/app/Modules/Authentifier/Controllers/Login.php(56): Modules\Authentifier\Models\UserModel::selectID('admin')
#3 /app/app/Modules/Authentifier/Controllers/Login.php(48): Modules\Authentifier\Controllers\Login->loginActionDatabase('admin', '********')
#4 [internal function]: Modules\Authentifier\Controllers\Login->loginAction()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 19, 2016 17:20PM</p>

           <p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'authentifier.users' doesn't exist</p>

           <p><strong>Code:</strong> 42S02</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(53): Helpers\Database->select('SELECT user_id ...', Array, 2)
#2 /app/app/Modules/Authentifier/Controllers/Login.php(56): Modules\Authentifier\Models\UserModel::selectID('admin')
#3 /app/app/Modules/Authentifier/Controllers/Login.php(48): Modules\Authentifier\Controllers\Login->loginActionDatabase('admin', '********')
#4 [internal function]: Modules\Authentifier\Controllers\Login->loginAction()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 19, 2016 17:21PM</p>

           <p><strong>Message:</strong> SQLSTATE[42000] [1049] Unknown database 'authentifier'</p>

           <p><strong>Code:</strong> 1049</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 61</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(61): PDO->__construct('mysql:host=loca...', 'admin', '********')
#1 /app/app/Modules/Authentifier/Models/UserModel.php(48): Helpers\Database::get()
#2 /app/app/Modules/Authentifier/Controllers/Login.php(56): Modules\Authentifier\Models\UserModel::selectID('admin')
#3 /app/app/Modules/Authentifier/Controllers/Login.php(48): Modules\Authentifier\Controllers\Login->loginActionDatabase('admin', '********')
#4 [internal function]: Modules\Authentifier\Controllers\Login->loginAction()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<p>Error on Mar 19, 2016 17:22PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Controllers/Admin.php on line 38</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 19, 2016 17:37PM</p>

           <p><strong>Message:</strong> SQLSTATE[42000] [1049] Unknown database 'authentifier'</p>

           <p><strong>Code:</strong> 1049</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 61</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(61): PDO->__construct('mysql:host=loca...', 'admin', '********')
#1 /app/app/Modules/Authentifier/Models/AdminModel.php(17): Helpers\Database::get()
#2 /app/app/Modules/Authentifier/Controllers/Admin.php(29): Modules\Authentifier\Models\AdminModel::selectAllUsers()
#3 [internal function]: Modules\Authentifier\Controllers\Admin->usersManagementPanel()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<p>Error on Mar 19, 2016 17:38PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Controllers/Admin.php on line 38</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 19, 2016 18:26PM</p>

           <p><strong>Message:</strong> SQLSTATE[42000] [1049] Unknown database 'authentifier'</p>

           <p><strong>Code:</strong> 1049</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 61</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(61): PDO->__construct('mysql:host=loca...', 'admin', '********')
#1 /app/app/Modules/Authentifier/Models/AdminModel.php(17): Helpers\Database::get()
#2 /app/app/Modules/Authentifier/Controllers/Admin.php(29): Modules\Authentifier\Models\AdminModel::selectAllUsers()
#3 [internal function]: Modules\Authentifier\Controllers\Admin->usersManagementPanel()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 19, 2016 20:00PM</p>

           <p><strong>Message:</strong> SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'user_failed_logins + 1' for column 'user_failed_logins' at row 1</p>

           <p><strong>Code:</strong> HY000</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 173</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(173): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/LoginModel.php(31): Helpers\Database->update('users', Array, Array)
#2 /app/app/Modules/Authentifier/Controllers/Login.php(71): Modules\Authentifier\Models\LoginModel::loginFailed('3')
#3 /app/app/Modules/Authentifier/Controllers/Login.php(48): Modules\Authentifier\Controllers\Login->loginActionDatabase('administrator', '********')
#4 [internal function]: Modules\Authentifier\Controllers\Login->loginAction()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 19, 2016 20:04PM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_failed_model' in 'field list'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 173</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(173): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/LoginModel.php(32): Helpers\Database->update('users', Array, Array)
#2 /app/app/Modules/Authentifier/Controllers/Login.php(71): Modules\Authentifier\Models\LoginModel::loginFailed(false)
#3 /app/app/Modules/Authentifier/Controllers/Login.php(48): Modules\Authentifier\Controllers\Login->loginActionDatabase('admin', '********')
#4 [internal function]: Modules\Authentifier\Controllers\Login->loginAction()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<p>Error on Mar 19, 2016 20:04PM - Illegal string offset 'user_failed_logins' in /app/app/Modules/Authentifier/Models/LoginModel.php on line 30</p><p>Error on Mar 19, 2016 20:05PM - Illegal string offset 'user_failed_logins' in /app/app/Modules/Authentifier/Models/LoginModel.php on line 30</p><p>Error on Mar 19, 2016 20:05PM - Illegal string offset 'user_failed_logins' in /app/app/Modules/Authentifier/Models/LoginModel.php on line 31</p><p>Error on Mar 19, 2016 20:05PM - Illegal string offset 'user_failed_logins' in /app/app/Modules/Authentifier/Models/LoginModel.php on line 31</p><p>Error on Mar 19, 2016 20:07PM - Illegal string offset 'user_failed_logins' in /app/app/Modules/Authentifier/Models/LoginModel.php on line 29</p><p>Error on Mar 19, 2016 20:07PM - Illegal string offset 'user_failed_logins' in /app/app/Modules/Authentifier/Models/LoginModel.php on line 29</p><p>Error on Mar 19, 2016 20:08PM - Illegal string offset 'user_failed_logins' in /app/app/Modules/Authentifier/Models/LoginModel.php on line 31</p><p>Error on Mar 19, 2016 20:08PM - Illegal string offset 'user_failed_logins' in /app/app/Modules/Authentifier/Models/LoginModel.php on line 31</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 20, 2016 13:25PM</p>

           <p><strong>Message:</strong> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@gmail.com' at line 1</p>

           <p><strong>Code:</strong> 42000</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModelTest.php(44): Helpers\Database->select('SELECT * FROM u...', Array, 8, 'Modules\\Authent...')
#2 /app/app/Controllers/Welcome.php(62): Modules\Authentifier\Models\UserModelTest::findByUserEMail('alex62d@gmail.c...')
#3 /app/app/Controllers/Welcome.php(45): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 20, 2016 13:25PM</p>

           <p><strong>Message:</strong> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@gmail.com' at line 1</p>

           <p><strong>Code:</strong> 42000</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModelTest.php(44): Helpers\Database->select('SELECT * FROM u...', Array, 8, 'Modules\\Authent...')
#2 /app/app/Controllers/Welcome.php(62): Modules\Authentifier\Models\UserModelTest::findByUserEMail('alex62d@gmail.c...')
#3 /app/app/Controllers/Welcome.php(45): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 20, 2016 13:25PM</p>

           <p><strong>Message:</strong> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\@gmail.com' at line 1</p>

           <p><strong>Code:</strong> 42000</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModelTest.php(44): Helpers\Database->select('SELECT * FROM u...', Array, 8, 'Modules\\Authent...')
#2 /app/app/Controllers/Welcome.php(62): Modules\Authentifier\Models\UserModelTest::findByUserEMail('alex62d\\@gmail....')
#3 /app/app/Controllers/Welcome.php(45): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 20, 2016 13:25PM</p>

           <p><strong>Message:</strong> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\@gmail.com' at line 1</p>

           <p><strong>Code:</strong> 42000</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModelTest.php(44): Helpers\Database->select('SELECT * FROM u...', Array, 8, 'Modules\\Authent...')
#2 /app/app/Controllers/Welcome.php(62): Modules\Authentifier\Models\UserModelTest::findByUserEMail('alex62d\\@gmail....')
#3 /app/app/Controllers/Welcome.php(45): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 20, 2016 13:26PM</p>

           <p><strong>Message:</strong> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@gmail.com' at line 1</p>

           <p><strong>Code:</strong> 42000</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModelTest.php(44): Helpers\Database->select('SELECT * FROM u...', Array, 8, 'Modules\\Authent...')
#2 /app/app/Controllers/Welcome.php(62): Modules\Authentifier\Models\UserModelTest::findByUserEMail('alex62d@gmail.c...')
#3 /app/app/Controllers/Welcome.php(45): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 20, 2016 13:27PM</p>

           <p><strong>Message:</strong> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@gmail.com' at line 1</p>

           <p><strong>Code:</strong> 42000</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModelTest.php(44): Helpers\Database->select('SELECT * FROM u...', Array, 8, 'Modules\\Authent...')
#2 /app/app/Controllers/Welcome.php(62): Modules\Authentifier\Models\UserModelTest::findByUserEMail('alex62d@gmail.c...')
#3 /app/app/Controllers/Welcome.php(45): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 20, 2016 13:29PM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'alex62d' in 'where clause'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModelTest.php(39): Helpers\Database->select('SELECT * FROM u...', Array, 8, 'Modules\\Authent...')
#2 /app/app/Controllers/Welcome.php(65): Modules\Authentifier\Models\UserModelTest::findByUserName('alex62d')
#3 /app/app/Controllers/Welcome.php(45): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<p>Error on Mar 20, 2016 18:06PM - call_user_func_array() expects parameter 1 to be a valid callback, class 'Modules\Authentifier\Controllers\Login' does not have a method 'logout' in /app/app/Core/Router.php on line 126</p><p>Error on Mar 20, 2016 18:36PM - get_class_vars() expects parameter 1 to be string, object given in /app/app/Modules/Authentifier/Controllers/Login.php on line 62</p><p>Error on Mar 20, 2016 19:48PM - get_object_vars() expects parameter 1 to be object, null given in /app/app/Controllers/Welcome.php on line 55</p><p>Error on Mar 20, 2016 19:48PM - get_object_vars() expects parameter 1 to be object, null given in /app/app/Controllers/Welcome.php on line 55</p><p>Error on Mar 20, 2016 19:48PM - get_object_vars() expects parameter 1 to be object, null given in /app/app/Controllers/Welcome.php on line 55</p><p>Error on Mar 20, 2016 23:11PM - get_object_vars() expects parameter 1 to be object, null given in /app/app/Controllers/Welcome.php on line 55</p><p>Error on Mar 20, 2016 23:12PM - get_object_vars() expects parameter 1 to be object, null given in /app/app/Controllers/Welcome.php on line 55</p><p>Error on Mar 20, 2016 23:12PM - get_object_vars() expects parameter 1 to be object, null given in /app/app/Controllers/Welcome.php on line 55</p><p>Error on Mar 20, 2016 23:12PM - get_object_vars() expects parameter 1 to be object, null given in /app/app/Controllers/Welcome.php on line 55</p><p>Error on Mar 20, 2016 23:12PM - get_object_vars() expects parameter 1 to be object, null given in /app/app/Controllers/Welcome.php on line 55</p><p>Error on Mar 20, 2016 23:13PM - get_object_vars() expects parameter 1 to be object, null given in /app/app/Controllers/Welcome.php on line 55</p><p>Error on Mar 22, 2016 19:50PM - get_object_vars() expects exactly 1 parameter, 2 given in /app/app/Modules/Authentifier/Controllers/Admin.php on line 37</p><p>Error on Mar 22, 2016 19:50PM - get_object_vars() expects exactly 1 parameter, 2 given in /app/app/Modules/Authentifier/Controllers/Admin.php on line 37</p><p>Error on Mar 22, 2016 19:51PM - get_object_vars() expects exactly 1 parameter, 2 given in /app/app/Modules/Authentifier/Controllers/Admin.php on line 37</p><p>Error on Mar 22, 2016 19:58PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Controllers/Admin.php on line 37</p><p>Error on Mar 22, 2016 21:39PM - Missing argument 1 for Modules\Authentifier\Controllers\Admin::userDelete(), called in /app/app/Modules/Authentifier/Controllers/Admin.php on line 53 and defined in /app/app/Modules/Authentifier/Controllers/Admin.php on line 60</p><p>Error on Mar 22, 2016 21:40PM - Missing argument 1 for Modules\Authentifier\Controllers\Admin::userDelete(), called in /app/app/Modules/Authentifier/Controllers/Admin.php on line 53 and defined in /app/app/Modules/Authentifier/Controllers/Admin.php on line 60</p><p>Error on Mar 22, 2016 21:40PM - Missing argument 1 for Modules\Authentifier\Controllers\Admin::userDelete(), called in /app/app/Modules/Authentifier/Controllers/Admin.php on line 53 and defined in /app/app/Modules/Authentifier/Controllers/Admin.php on line 60</p><p>Error on Mar 23, 2016 17:42PM - require(/app/app/views/test.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 23, 2016 17:45PM - require(/app/app/views/Modules/Authentifier/Profile_user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 23, 2016 17:45PM - require(/app/app/views/Modules/Authentifier/Profile_user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 23, 2016 17:45PM - require(/app/app/views/Modules/Authentifier/Profile_user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 23, 2016 17:45PM - require(/app/app/views/Modules/Authentifier/Profile_user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 23, 2016 17:46PM - require(/app/app/views/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 23, 2016 17:46PM - require(/app/app/views/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 23, 2016 17:46PM - require(/app/app/views/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 23, 2016 17:48PM - require(/app/app/views//Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 23, 2016 17:48PM - require(/app/app/views//Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 23, 2016 17:49PM - require(/app/app/views/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 23, 2016 17:49PM - require(/app/app/views/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 23, 2016 17:49PM - require(/app/app/views/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 23, 2016 17:49PM - require(/app/app/views/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 23, 2016 17:49PM - require(/app/app/views/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 23, 2016 17:49PM - require(/app/app/views/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 23, 2016 17:49PM - require(/app/app/views/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 34</p><p>Error on Mar 23, 2016 17:51PM - require(/app/app/Modules/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 23, 2016 17:51PM - require(/app/app/Modules/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 23, 2016 17:51PM - require(/app/app/Modules/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 23, 2016 17:53PM - require(/app/app/Modules/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 23, 2016 17:53PM - require(/app/app/Modules/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 23, 2016 17:53PM - require(/app/app/Modules/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 23, 2016 17:53PM - require(/app/app/Modules/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 23, 2016 17:53PM - require(/app/app/Modules/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 23, 2016 17:53PM - require(/app/app/Modules/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 23, 2016 18:01PM - require(/app/app/Modules/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 23, 2016 18:01PM - require(/app/app/Modules/app/Modules/Authentifier/Views/Profile/user_profile.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 25, 2016 22:52PM - stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /app/app/Helpers/PhpMailer/Smtp.php on line 224</p><p>Error on Mar 25, 2016 22:53PM - stream_socket_client(): unable to connect to ssl://smtp.goodgle.com:465 (Connection timed out) in /app/app/Helpers/PhpMailer/Smtp.php on line 224</p><p>Error on Mar 25, 2016 23:01PM - constant(): Couldn't find constant MAIL_SMTP_SERVER in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 35</p><p>Error on Mar 25, 2016 23:05PM - constant(): Couldn't find constant MAIL_SMTP_SERVER in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 35</p><p>Error on Mar 25, 2016 23:06PM - constant(): Couldn't find constant MAIL_SMTP_SERVER in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 35</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 25, 2016 23:08PM</p>

           <p><strong>Message:</strong> SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)</p>

           <p><strong>Code:</strong> 2002</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 61</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(61): PDO->__construct('mysql:host=loca...', 'admin', '********')
#1 /app/app/Modules/Authentifier/Models/UserModelTest.php(50): Helpers\Database::get()
#2 /app/app/Modules/Authentifier/Models/LoginModel.php(36): Modules\Authentifier\Models\UserModelTest::findByUserID(NULL)
#3 /app/app/Modules/Authentifier/Controllers/Login.php(85): Modules\Authentifier\Models\LoginModel::checkLoginSession(NULL, '18sdem2d6ljl5uv...')
#4 /app/app/Modules/Authentifier/Controllers/Authentifier.php(34): Modules\Authentifier\Controllers\Login::userLoggedIn()
#5 /app/app/Helpers/Hooks.php(161): Modules\Authentifier\Controllers\Authentifier->__construct()
#6 /app/app/Core/routes.php(20): Helpers\Hooks->run('routes')
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<p>Error on Mar 25, 2016 23:15PM - stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol in /app/app/Helpers/PhpMailer/Smtp.php on line 224</p><p>Error on Mar 25, 2016 23:16PM - stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol in /app/app/Helpers/PhpMailer/Smtp.php on line 224</p><p>Error on Mar 25, 2016 23:16PM - stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol in /app/app/Helpers/PhpMailer/Smtp.php on line 224</p><p>Error on Mar 25, 2016 23:46PM - include_once(/app/Modules/Authentifier/Views/Profile/profile_update_form.php): failed to open stream: No such file or directory in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 44</p><p>Error on Mar 26, 2016 0:29AM - array_merge(): Argument #2 is not an array in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 48</p><p>Error on Mar 27, 2016 14:53PM - file_get_contents(ok): failed to open stream: No such file or directory in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 48</p><p>Error on Mar 27, 2016 14:53PM - file_get_contents(ok): failed to open stream: No such file or directory in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 48</p><p>Error on Mar 27, 2016 14:55PM - file_get_contents(Modules/Helpers/Authmail/Templates/register_validation_mail.php): failed to open stream: No such file or directory in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 49</p><p>Error on Mar 27, 2016 14:55PM - file_get_contents(Modules/Helpers/Authmail/Templates/register_validation_mail.php): failed to open stream: No such file or directory in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 49</p><p>Error on Mar 27, 2016 14:55PM - file_get_contents(/Modules/Helpers/Authmail/Templates/register_validation_mail.php): failed to open stream: No such file or directory in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 49</p><p>Error on Mar 27, 2016 14:56PM - file_get_contents(app/Modules/Helpers/Authmail/Templates/register_validation_mail.php): failed to open stream: No such file or directory in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 49</p><p>Error on Mar 27, 2016 14:56PM - file_get_contents(/app/Modules/Helpers/Authmail/Templates/register_validation_mail.php): failed to open stream: No such file or directory in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 49</p><p>Error on Mar 27, 2016 14:57PM - file_get_contents(/app/app/Modules/Helpers/Authmail/Templates/register_validation_mail.php): failed to open stream: No such file or directory in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 49</p><p>Error on Mar 27, 2016 14:58PM - file_get_contents() expects parameter 1 to be a valid path, array given in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 50</p><p>Error on Mar 27, 2016 14:58PM - file_get_contents(Templates/register_validation_mail.php): failed to open stream: No such file or directory in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 49</p><p>Error on Mar 27, 2016 14:59PM - file_get_contents(../Templates/register_validation_mail.php): failed to open stream: No such file or directory in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 49</p><p>Error on Mar 27, 2016 15:00PM - file_get_contents(../Templates/register_validation_mail.php): failed to open stream: No such file or directory in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 50</p><p>Error on Mar 27, 2016 15:00PM - file_get_contents(../Templates/register_validation_mail.php): failed to open stream: No such file or directory in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 50</p><p>Error on Mar 27, 2016 15:00PM - file_get_contents(../Templates/register_validation_mail.php): failed to open stream: No such file or directory in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 50</p><p>Error on Mar 27, 2016 15:00PM - file_get_contents(./Templates/register_validation_mail.php): failed to open stream: No such file or directory in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 49</p><p>Error on Mar 27, 2016 15:01PM - file_get_contents(Templates/register_validation_mail.php): failed to open stream: No such file or directory in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 49</p><p>Error on Mar 27, 2016 15:11PM - file_get_contents() expects parameter 3 to be resource, array given in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 50</p><p>Error on Mar 27, 2016 15:14PM - str_replace() expects at least 3 parameters, 2 given in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 51</p><p>Error on Mar 27, 2016 16:08PM - file_get_contents(/Modules/Authentifier/Helpers/AuthMail/Templates/register_validation_mail.php): failed to open stream: No such file or directory in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 50</p><p>Error on Mar 27, 2016 16:08PM - file_get_contents(Modules/Authentifier/Helpers/AuthMail/Templates/register_validation_mail.php): failed to open stream: No such file or directory in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 50</p><p>Error on Mar 27, 2016 16:16PM - preg_replace(): No ending delimiter '~' found in /app/app/Modules/Authentifier/Helpers/AuthMail/AuthMail.php on line 91</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 27, 2016 19:10PM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_last_failed_logins' in 'field list'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 173</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(173): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/LoginModel.php(33): Helpers\Database->update('users', Array, Array)
#2 /app/app/Modules/Authentifier/Controllers/Login.php(76): Modules\Authentifier\Models\LoginModel->loginFailed()
#3 /app/app/Modules/Authentifier/Controllers/Login.php(49): Modules\Authentifier\Controllers\Login->loginActionDatabase('alex62d', 'okokokok')
#4 [internal function]: Modules\Authentifier\Controllers\Login->loginAction()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
