<p>Error on Mar 09, 2016 0:00AM - Invalid argument supplied for foreach() in /app/app/Helpers/Gump.php on line 137</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 09, 2016 0:10AM</p>

           <p><strong>Message:</strong> Filter method 'satinize' does not exist.</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> /app/app/Helpers/Gump.php</p>

           <p><strong>Line:</strong> 596</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Gump.php(227): Helpers\Gump->filter(Array, Array)
#1 /app/app/Modules/Authentifier/Helpers/InputValidation.php(102): Helpers\Gump->run(Array)
#2 /app/app/Modules/Authentifier/Controllers/Register.php(42): Modules\Authentifier\Helpers\InputValidation::inputsValidation(Array)
#3 [internal function]: Modules\Authentifier\Controllers\Register->registerAction()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 09, 2016 0:10AM</p>

           <p><strong>Message:</strong> Filter method 'satinize' does not exist.</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> /app/app/Helpers/Gump.php</p>

           <p><strong>Line:</strong> 596</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Gump.php(227): Helpers\Gump->filter(Array, Array)
#1 /app/app/Modules/Authentifier/Helpers/InputValidation.php(102): Helpers\Gump->run(Array)
#2 /app/app/Modules/Authentifier/Controllers/Register.php(42): Modules\Authentifier\Helpers\InputValidation::inputsValidation(Array)
#3 [internal function]: Modules\Authentifier\Controllers\Register->registerAction()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 09, 2016 0:11AM</p>

           <p><strong>Message:</strong> Filter method 'satinize_string' does not exist.</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> /app/app/Helpers/Gump.php</p>

           <p><strong>Line:</strong> 596</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Gump.php(227): Helpers\Gump->filter(Array, Array)
#1 /app/app/Modules/Authentifier/Helpers/InputValidation.php(102): Helpers\Gump->run(Array)
#2 /app/app/Modules/Authentifier/Controllers/Register.php(42): Modules\Authentifier\Helpers\InputValidation::inputsValidation(Array)
#3 [internal function]: Modules\Authentifier\Controllers\Register->registerAction()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<p>Error on Mar 09, 2016 0:29AM - Missing argument 2 for Modules\Authentifier\Models\UserModel::newUser(), called in /app/app/Modules/Authentifier/Controllers/Register.php on line 59 and defined in /app/app/Modules/Authentifier/Models/UserModel.php on line 35</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 09, 2016 0:36AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_captcha' in 'field list'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 131</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(131): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(37): Helpers\Database->insert('users', Array)
#2 /app/app/Modules/Authentifier/Controllers/Register.php(59): Modules\Authentifier\Models\UserModel->insertUser(Array)
#3 [internal function]: Modules\Authentifier\Controllers\Register->registerAction()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 09, 2016 0:38AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_captcha' in 'field list'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 131</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(131): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(37): Helpers\Database->insert('users', Array)
#2 /app/app/Modules/Authentifier/Controllers/Register.php(61): Modules\Authentifier\Models\UserModel->insertUser(Array)
#3 [internal function]: Modules\Authentifier\Controllers\Register->registerAction()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 09, 2016 0:38AM</p>

           <p><strong>Message:</strong> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0,1,2) VALUES ('alexandre', NULL, 'cccd0608')' at line 1</p>

           <p><strong>Code:</strong> 42000</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 131</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(131): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(37): Helpers\Database->insert('users', Array)
#2 /app/app/Modules/Authentifier/Controllers/Register.php(61): Modules\Authentifier\Models\UserModel->insertUser(Array)
#3 [internal function]: Modules\Authentifier\Controllers\Register->registerAction()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<p>Error on Mar 09, 2016 0:43AM - Missing argument 1 for Helpers\Database::insert(), called in /app/app/Modules/Authentifier/Models/UserModel.php on line 38 and defined in /app/app/Helpers/Database.php on line 118</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 09, 2016 0:44AM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'alexandre' for key 'user_name'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 131</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(131): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(37): Helpers\Database->insert('users', Array)
#2 /app/app/Modules/Authentifier/Controllers/Register.php(61): Modules\Authentifier\Models\UserModel->insertUser(Array)
#3 [internal function]: Modules\Authentifier\Controllers\Register->registerAction()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 09, 2016 0:45AM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'alexandre' for key 'user_name'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 131</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(131): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(37): Helpers\Database->insert('users', Array)
#2 /app/app/Modules/Authentifier/Controllers/Register.php(66): Modules\Authentifier\Models\UserModel->insertUser(Array)
#3 [internal function]: Modules\Authentifier\Controllers\Register->registerAction()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<p>Error on Mar 09, 2016 1:24AM - require(/app/app/Modules//Authentifier/Views/Register/feedback.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 09, 2016 1:24AM - require(/app/app/Modules/Authentifier/Views/Register/feedback.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 09, 2016 1:30AM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Views/Feedback/feedback.php on line 31</p><p>Error on Mar 09, 2016 1:32AM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Views/Feedback/feedback.php on line 14</p><p>Error on Mar 09, 2016 1:33AM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Views/Feedback/feedback.php on line 14</p><p>Error on Mar 09, 2016 1:34AM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Views/Feedback/feedback.php on line 14</p><p>Error on Mar 09, 2016 1:37AM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Views/Feedback/feedback.php on line 14</p><p>Error on Mar 09, 2016 1:37AM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Views/Feedback/feedback.php on line 14</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 09, 2016 2:44AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'alexandre' in 'where clause'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(47): Helpers\Database->select('\n          SELE...')
#2 /app/app/Modules/Authentifier/Controllers/Register.php(75): Modules\Authentifier\Models\UserModel->exist('alexandre')
#3 [internal function]: Modules\Authentifier\Controllers\Register->registerAction()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 09, 2016 2:48AM</p>

           <p><strong>Message:</strong> SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens</p>

           <p><strong>Code:</strong> HY093</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(46): Helpers\Database->select('SELECT 1 FROM u...', Array)
#2 /app/app/Modules/Authentifier/Controllers/Register.php(75): Modules\Authentifier\Models\UserModel->exist('alexandre')
#3 [internal function]: Modules\Authentifier\Controllers\Register->registerAction()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
